### GET /

GET http://localhost:5006/



#### LOGIN a user POST /auth/login
POST http://localhost:5006/auth/login
Content-Type: application/json


{
    "username": "admsids@gmail.com",
    "password": "admain"
}


### REGISTER a user POST /auth/register
POST http://localhost:5006/auth/register
Content-Type: application/json

{
    "username": "admsid2s@gmail.com",
    "password": "admain"
}


### Fetch all todos GET /todo (protected)
GET http://localhost:5006/todos
Authorization: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3MTAxNzcwLCJleHAiOjE3MzcxMDUzNzB9.sOksKmqH5eR05fOjztjer_cGqIMoqXAwufWoFzvFAyQ

### Creates  todos GET /todo (protected)
POST http://localhost:5006/todos
Authorization: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3MTAxNzcwLCJleHAiOjE3MzcxMDUzNzB9.sOksKmqH5eR05fOjztjer_cGqIMoqXAwufWoFzvFAyQ
Content-Type: application/json


{
    "task":" you should be able to eat from the spoon and fork by the end of the day"
}

### Update a todo PUT /todo/:id (protected)
PUT http://localhost:5006/todos/3
Authorization: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3MTAxNzcwLCJleHAiOjE3MzcxMDUzNzB9.sOksKmqH5eR05fOjztjer_cGqIMoqXAwufWoFzvFAyQ
Content-Type: application/json

{
    "completed": 1
}

### Delete a todo DELETE /todo/:id (protected)
DELETE http://localhost:5006/todos/3
Authorization: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3MTAxNzcwLCJleHAiOjE3MzcxMDUzNzB9.sOksKmqH5eR05fOjztjer_cGqIMoqXAwufWoFzvFAyQ
Content-Type: application/json

{
    "completed": 1
}